### ISSUE TITLE
🛠 Tooling: build:release artifacts should always be committed to the main branch

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/all-contributors-auto-action#170]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/all-contributors-auto-action/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This action's `main` branch hasn't updated its `dist/` directory in 7 months. That means the published action doesn't include updates made to source files or packages... including #137.

#137 not being published is the root cause of https://github.com/JoshuaKGoldberg/all-contributors-for-repository/issues/199.

**Comment by JoshuaKGoldberg** [comment]
Fixed by #171.

**Comment by JoshuaKGoldberg** [comment]
fyi @johnyreilly, this might be of interest to you... I'm not sold that this is the right solution.

**Comment by johnnyreilly** [comment]
Running in the precommit hook you mean? I do that - prompted by @jakebailey 

I also have this workflow that checks dist is up to date 

https://github.com/johnnyreilly/schemar/blob/main/.github/workflows/check-dist.yml
